{% set name = "kaolin" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIAGameWorks/kaolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7fa6b794d83fca9b4a1eb93b13ead60767b42d5a8a25162ee73be3cead1a8c8c

build:
  number: 1
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - pytorch <=1.9.0,>=1.5.0
  host:
    - pip
    - python
    - cython ==0.29.20
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2.0
    - pillow >=8.0.0
    - tqdm
    - pytorch <=1.9.0,>=1.5.0
   
test:
  imports:
    - kaolin

about:
  home: https://developer.nvidia.com/nvidia-kaolin 
  license: Apache-2.0 
  license_family: APACHE
  license_file: LICENSE
  summary: 'A Pytorch Library for Accelerating 3D Deep Learning Research '
  description: |
      NVIDIA Kaolin library provides a PyTorch API for working with a variety
      of 3D representations and includes a growing collection of
      GPU-optimized operations such as modular differentiable rendering,
      fast conversions between representations, data loading,
      3D checkpoints and more.
  dev_url: https://github.com/NVIDIAGameWorks/kaolin
  doc_url: https://kaolin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
